In [32]:
#Importamos las librerias
import numpy as np
import warnings
warnings.filterwarnings("ignore")

# Numpy Array

In [40]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [41]:
type(list1)

list

In [42]:
#Convertimos la lista en un array de numpy
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [47]:
type(arr1)

numpy.ndarray

In [48]:
#Array de nros
arr1.dtype

dtype('int32')

In [49]:
#Convierto en flotante
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [50]:
#Veamos que pasa si tengo diferentes tipos de datos
list2 = [10,'esto es un texto']
arr_example = np.array(list2)
arr_example

array(['10', 'esto es un texto'], dtype='<U16')

In [8]:
#Generamos un array nuevo
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [10]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [11]:
arr3 = np.arange(0,10)
arr3.size

10

In [12]:
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#Dimension
arr3.ndim

1

In [15]:
#Longitud del array
len(arr3)

10

In [16]:
#Arrays de 0
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
#De unos...
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
#Array para que repita un valor
np.repeat(10,5)

array([10, 10, 10, 10, 10])

In [20]:
#Repite el objeto a tres veces
a= np.array([10,20,30])
np.repeat(a,3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [22]:
#Creando arrays de random
np.random.random(4)

array([0.40547631, 0.87332714, 0.79037523, 0.54174159])

In [23]:
#Arrays intergers - 5 valores
np.random.randint(0,500,5)

array([177, 493, 321, 200, 338])

In [24]:
#Arrays intergers - 10 valores
np.random.randint(0,500,10)

array([128, 451, 468, 253,   0,  72,  83,  28,  69, 417])

In [25]:
#Uso de una semilla
np.random.seed(123)
np.random.randint(0,100,10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [26]:
#Cambiando la semilla
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [27]:
#Creando un array con una distribucion uniforme
f1 = np.random.uniform(5,10, size=(10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [28]:
#Extraigo el valor flotante!
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [29]:
#Convierto el array en integer
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [30]:
#Arrays con una distribucion normal(mean=0 and variance=1)
b2 =np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [31]:
#Viendo los indices y los valores del array
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60
